### ISSUE TITLE
Broken latest release

### ISSUE THREAD

**Issue by antonio-fr** [martinpaljak/ant-javacard#82]
Using the ant-javacard jar to build our CAP files, it now generates a lot of different errors and doesn't compile the cap. But everything is OK when using the previous version.

I spent some time to figure out what's wrong, and ultimately using the previous version, it works well, as before.

I use JDK 8 (1.8.0).

With jckit/targetkit = 3.0.5u4/3.0.5u4, I got something like that :
```
...
  [convert] [ INFO: ] conversion completed with 0 errors and 1 warnings.
   [verify] Verification passed

BUILD FAILED
build.xml:6: java.lang.UnsupportedOperationException
        at com.sun.nio.zipfs.ZipPath.toFile(ZipPath.java:660)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList.forEach(ArrayList.java:1259)
        at java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:390)
        at java.util.stream.Sink$ChainedReference.end(Sink.java:258)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at pro.javacard.capfile.CAPFile.strip(CAPFile.java:435)
        at pro.javacard.ant.JavaCard$JCCap.execute(JavaCard.java:795)
        at pro.javacard.ant.JavaCard.execute(JavaCard.java:152)
        at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:299)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
        at org.apache.tools.ant.Task.perform(Task.java:350)
        at org.apache.tools.ant.Target.execute(Target.java:449)
        at org.apache.tools.ant.Target.performTasks(Target.java:470)
        at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
        at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
        at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
        at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
        at org.apache.tools.ant.Main.runBuild(Main.java:818)
        at org.apache.tools.ant.Main.startAnt(Main.java:223)
        at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
        at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

With jckit/targetkit = 3.10r20210706/3.0.5u4, I get that :
```
...
  [convert] [ INFO: ] Converter [v3.1.0]warning: You did not supply export file for the previous minor version of the package
  [convert]
  [convert] [ INFO: ]     Copyright (c) 1998, 2021, Oracle and/or its affiliates. All rights reserved.
  [convert]
  [convert]
  [convert] [ INFO: ] conversion completed with 0 errors and 1 warnings.

BUILD FAILED
```

When using v21.12.31, everything works fine, our cap is compiled and verified in both cases.
That suggests there are some regressions in the 23.04.03 latest release.

**Comment by martinpaljak** [comment]
Thanks for reporting! I rolled back the release status. There's something wrong that allowed the tests to not run/pass as well, so need to investigate
